WafaTailor/Controllers/SaleOrderController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WafaTailor.Filter;
using WafaTailor.Models;

namespace WafaTailor.Controllers
{
    public class SaleOrderController : AdminBaseController
    {
        // GET: SaleOrder
        public ActionResult SaleOrder(SaleOrder obj, string BillId, string paymentid)
        {
            #region Shop
            List<SelectListItem> ddlShop = new List<SelectListItem>();
            DataSet ds1 = obj.GetShopNameDetails();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                int count = 0;
                foreach (DataRow r in ds1.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        ddlShop.Add(new SelectListItem { Text = "Select Shop", Value = "0" });
                    }
                    ddlShop.Add(new SelectListItem { Text = r["ShopName"].ToString(), Value = r["Pk_ShopId"].ToString() });
                    count++;
                }
            }
            ViewBag.ddlShop = ddlShop;
            #endregion
            #region Customer
            List<SelectListItem> ddlcustomer = new List<SelectListItem>();
            DataSet ds = obj.GetCustomerDetails();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                int count = 0;
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        ddlcustomer.Add(new SelectListItem { Text = "Select Customer", Value = "0" });
                    }
                    ddlcustomer.Add(new SelectListItem { Text = r["CustomerName"].ToString(), Value = r["PK_UserId"].ToString() });
                    count++;
                }
            }
            ViewBag.ddlcustomer = ddlcustomer;
            #endregion

            if (BillId != null)
            {
                obj.BillId = BillId;
                obj.PaymentId = paymentid;
                DataSet ds2 = obj.GetBillDetails();
                if (ds2 != null && ds2.Tables[0].Rows.Count > 0 && ds2.Tables.Count > 0)
                {
                    obj.BillId = ds2.Tables[0].Rows[0]["Pk_BillId"].ToString();
                    obj.ShopId = ds2.Tables[0].Rows[0]["Fk_Shopid"].ToString();
                    obj.LoginId = ds2.Tables[0].Rows[0]["Name"].ToString();
                    obj.Mobile = ds2.Tables[0].Rows[0]["Mobile"].ToString();
                    obj.BillNo = ds2.Tables[0].Rows[0]["BillNo"].ToString();
                    obj.NoOfPiece = ds2.Tables[0].Rows[0]["NoOfPiece"].ToString();
                    obj.OriginalPrice = ds2.Tables[0].Rows[0]["OriginalPrice"].ToString();
                    obj.NetAmount = ds2.Tables[0].Rows[0]["FinalAmount"].ToString();
                    obj.Pk_UserId = ds2.Tables[0].Rows[0]["Fk_UserId"].ToString();
                    obj.TotalDeliveredPiece = ds2.Tables[0].Rows[0]["TotalDeliveredPiece"].ToString();
                }
            }

            return View(obj);
        }


        [HttpPost]
        public JsonResult SaveSaleOrderDetails(SaleOrder order, string dataValue)
        {
            try
            {
                //order.SaleOrderDate = string.IsNullOrEmpty(order.SaleOrderDate) ? null : Common.ConvertToSystemDate(order.SaleOrderDate, "dd/MM/yyyy");
                string Name = "";
                string Piece = "";
                string OriginalPrice = "";
                string Discount = "";
                string FinalPrice = "";
                string SaleDate = "";
                string Description = "";
                //int rowsno = 0;
                var isValidModel = TryUpdateModel(order);
                var jss = new JavaScriptSerializer();
                var jdv = jss.Deserialize<dynamic>(dataValue);

                DataTable dtorder = new DataTable();
                dtorder.Columns.Add("Name");
                dtorder.Columns.Add("Piece");
                dtorder.Columns.Add("OriginalPrice");
                dtorder.Columns.Add("Discount");
                dtorder.Columns.Add("FinalPrice");
                dtorder.Columns.Add("SaleDate");
                dtorder.Columns.Add("Description");
                //dtorder.Columns.Add("rowsno");
                DataTable dt = new DataTable();
                dt = JsonConvert.DeserializeObject<DataTable>(jdv["dataValue"]);
                int numberOfRecords = dt.Rows.Count;
                //foreach (DataRow row in dt.Rows)

                foreach (DataRow row in dt.Rows)
                {
                    Name = "";
                    Piece = row["Piece"].ToString();
                    OriginalPrice = row["OriginalPrice"].ToString();
                    Discount = row["Discount"].ToString();
                    FinalPrice = row["NetAmount"].ToString();
                    SaleDate = string.IsNullOrEmpty(row["SaleDate"].ToString()) ? null : Common.ConvertToSystemDate(row["SaleDate"].ToString(), "dd/MM/yyyy");
                    Description = row["Description"].ToString();

                    //rowsno = rowsno + 1;
                    dtorder.Rows.Add(Name, Piece, OriginalPrice, Discount, FinalPrice, SaleDate, Description);
                }
                order.dt = dtorder;
                order.Pk_UserId = order.Pk_UserId == "" ? null : order.Pk_UserId;
                order.AddedBy = Session["Pk_EmployeeId"].ToString();
                DataSet ds = order.SaveSaleOrder();
                if (ds != null && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0][0].ToString() == "1")
                    {
                        order.Result = "Yes";
                    }
                    else if (ds.Tables[0].Rows[0][0].ToString() == "0")
                    {
                        order.Result = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                    }
                }
                else
                {
                    order.Result = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                }
            }
            catch (Exception ex)
            {

                order.Result = ex.Message;
            }

            return new JsonResult { Data = new { status = order.Result } };
        }
        //public ActionResult SaveSaleOrderDetails(SaleOrder order, string SaleorderdataValue)
        //{

        //    try
        //    {
        //        string Description = "";
        //        string Amount = "";
        //        string DeliveryDate = "";
        //        var isValidModel = TryUpdateModel(order);
        //        var jss = new JavaScriptSerializer();
        //        var jdv = jss.Deserialize<dynamic>(SaleorderdataValue);
        //        DataTable dtSaleOrderDetails = new DataTable();
        //        dtSaleOrderDetails.Columns.Add("Description");
        //        dtSaleOrderDetails.Columns.Add("Amount");
        //        dtSaleOrderDetails.Columns.Add("DeliveryDate");

        //        DataTable dt = new DataTable();
        //        dt = JsonConvert.DeserializeObject<DataTable>(jdv["SaleorderAddData"]);
        //        int numberOfRecords = dt.Rows.Count;
        //        foreach (DataRow row in dt.Rows)
        //        {
        //            Description = row["Description"].ToString();
        //            Amount = row["Amount"].ToString();
        //            DeliveryDate = row["DeliveryDate"].ToString();

        //            DeliveryDate = string.IsNullOrEmpty(row["DeliveryDate"].ToString()) ? null : Common.ConvertToSystemDate(row["DeliveryDate"].ToString(), "dd/MM/yyyy");                  
        //            dtSaleOrderDetails.Rows.Add(Description, Amount, DeliveryDate);
        //        }
        //        order.dtSaleOrderDetails = dtSaleOrderDetails;
        //        order.AddedBy = "1";
        //        DataSet ds = new DataSet();
        //        ds = order.SaveSaleOrderDetails();
        //        if (ds != null && ds.Tables[0].Rows.Count > 0)
        //        {
        //            if (ds.Tables[0].Rows[0][0].ToString() == "1")
        //            {
        //                TempData["SaleOrder"] = "Sale Order Details saved successfully";

        //            }
        //            else if (ds.Tables[0].Rows[0][0].ToString() == "0")
        //            {
        //                TempData["SaleOrder"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
        //            }
        //        }
        //        else
        //        {
        //            TempData["SaleOrder"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
        //        }
        //    }
        //    catch (Exception ex)
        //    {

        //        TempData["SaleOrder"] = ex.Message;
        //    }

        //    return Json(order, JsonRequestBehavior.AllowGet);
        //}
        public ActionResult GetcustomerList()
        {
            SaleOrder obj = new SaleOrder();
            List<SaleOrder> lst = new List<SaleOrder>();
            DataSet ds = obj.GetCustomerDetails();
            if (ds != null && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    SaleOrder objList = new SaleOrder();
                    objList.Name = dr["CustomerName"].ToString();
                    objList.Mobile = dr["Mobile"].ToString();
                    objList.LoginId = dr["LoginId"].ToString();
                    lst.Add(objList);
                }
            }
            return Json(lst, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetUserDetails(string LoginId, string Mobile)
        {
            SaleOrder model = new SaleOrder();
            model.LoginId = LoginId;

WafaTailor/Views/SaleOrder/GenerateBill.cshtml
@model WafaTailor.Models.SaleOrder

@{
    ViewBag.Title = "GenerateBill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .mt-btn {
        margin-top: 20px;
    }
</style>
@using (Html.BeginForm("GenerateBill", "SaleOrder", FormMethod.Post, new { @id = "signupForm", enctype = "multipart/form-data" }))
{
    <div class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">SaleOrder</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item">
                            <a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Generate Bill</li>
                    </ol>
                </nav>
            </div>

            @if (TempData["InvoiceNo"] != null)
            { <div class="@TempData["Class"]">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h5 class="text-success"><i class="fa fa-check-circle"></i>&nbsp; @TempData["InvoiceNo"]</h5>
            </div>
            }
             @if (TempData["Bill"] != null)
            { <div class="@TempData["Class"]">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h5 class="text-success"><i class="fa fa-check-circle"></i>@TempData["Bill"]</h5>
            </div>
            }
            <div class="ms-auto">
                <div class="btn-group mt-2">
                    <a href="/Master/BankList" class="btn btn-light px-5">Back To List</a>
                </div>
            </div>
        </div>
        <hr />
        <div class="card">
            <div class="card-body">
                <div class="p-4 border rounded">
                    <div class="row g-3">
                        <div class="col-md-4">
                            <label for="input-1">Invoice No </label>

                            @Html.TextBoxFor(m => m.InvoiceNo, new { @class = "form-control", @Placeholder = "Invoice No", @readonly = "readonly" }) 
                            @*@Html.HiddenFor(m => m.PK_InvoiceNoID)*@
                        </div>

                        <div class="col-md-4">
                            <label for="input-1">Sale Order No </label>

                            @Html.TextBoxFor(m => m.SaleOrderNo, new { @class = "form-control", @Placeholder = "Sale Order No" }) 
                            @*@Html.HiddenFor(m => m.CampaignID)*@
                        </div>
                        <div class="col-md-4">
                            <div class="form-group row">
                                <div class="col-md-9 mt-4">
                                    <input type="submit" value="Get Details" class="btn btn-primary px-5" name="btnGetCampaignDetails" onclick="return validateCampaignNo()" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                            <table id="dataTable" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Action</th>
                                        <th>Service</th>
                                        <th>Sales Order No</th>
                                        <th>Order Date</th>
                                        <th>CustomerName</th>
                                        <th>CustomerMobile</th>
                                    </tr>
                                </thead>
                                @*<tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstsaleorder != null)
                                        {
                                            var j = 1;
                                            foreach (var item in Model.lstsaleorder)
                                            {
                                                <tr>
                                                    <td>
                                                        @if (item.LineStatus == "Unmapped")
                                                        {
                                                            <input type="checkbox" name="chkSO_@j" />
                                                        }
                                                    </td>
                                                    <td>@item.ServiceName</td>
                                                    <td>@item.SalesOrderNo</td>
                                                    <td>@item.OrderDate</td>
                                                    <td>@item.CustomerName</td>
                                                    <td>
                                                        @item.CustomerMobile
                                                        <input type="hidden" name="hdPON_@j" value="@item.PONumber" />
                                                        <input type="hidden" name="hdSaleOrderID_@j" value="@item.FK_SaleOrderId" />
                                                    </td>
                                                </tr>
                                                j++;
                                            }

                                            <input type="text" style="display:none" value="@j" id="hdrows" name="hdrows" />
                                        }
                                    }
                                </tbody>*@
                            </table>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-primary list-button mt-btn" name="btnSaveDetails" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

<script>
    $(document).ready(function () {
        //$('#InvoiceNo').val('AFLX/2019-20/');
        $("#divload").css({ display: "none" });

        var campaigns = [];
        $.ajax({
            url: "/SaleOrder/GetAllCampaigns",
            type: "Post",
            success: function (response) {
                if (response != null) {
                    $(response.lstCompaign).each(function (index, item) { // GETTING ERROR HERE
                        campaigns.push(item.CreativeName + "(" + item.CampaignNo + ")");
                    });
                    $('#CampaignNo').autocomplete({
                        source: campaigns,
                        select: function (event, ui) {
                            var str = ui.item.label;
                            var afterComma = str.substr(str.indexOf("(") + 1);
                            var citycode = afterComma.substr(0, afterComma.length - 1);
                            $('#CampaignID').val(citycode);

                        }
                    })
                }
            },
            error: function () {
                alert("Some Thing Wrong!");
            },
        });
    });
    function validateCampaignNo() {
        if ($("#InvoiceNo").val() == "") {
            $("#InvoiceNo").addClass("errortext");
            $("#InvoiceNo").focus();
            return false;
        }
        if ($("#CampaignNo").val() == "") {
            $("#CampaignNo").addClass("errortext");
            $("#CampaignNo").focus();
            return false;
        }
    }
</script>
<style>
    .errortext {
        border: 1px solid red !important;
        background-color: #ff00003b !important;
    }
</style>

WafaTailor/Views/SaleOrder/RefundSaleOrder.cshtml
@model WafaTailor.Models.SaleOrder

@{
    ViewBag.Title = "RefundSaleOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
<link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
@using (Html.BeginForm("RefundSaleOrder", "SaleOrder", FormMethod.Post, new { @Id = "form", @enctype = "multipart/Form-data" }))
{
    <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class="pull-left">
                        @*<div class="page-title"> Employee Registration</div>*@
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-12">
                    <div class="card card-box">
                        <div class="card-head">
                            <header>Refund Sale Order</header>
                            <span class="text-danger">
                                @TempData["Order"]
                            </span>
                            <a href="/SaleOrder/RefundSaleOrderList" class="btn btn-primary pull-right mr-10 mt-1 mb-1"><i class="fa fa-arrow-left"></i> Back to List</a>
                        </div>
                        <div class="card-body" id="bar-parent">
                            <form>
                                <div class="row">
                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormPassword">Bill Number <span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.BillNo, new { @class = "form-control", @placeholder = "Bill Number", @onchange = "return getBillNo();" })
                                        @Html.HiddenFor(m => m.BillNo)
                                    </div>

                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormEmail">Total Piece<span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.AvailableNoOfPiece, new { @class = "form-control", @Placeholder = "Total Piece", @readonly = "true" })
                                    </div>

                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormEmail">Refund Piece<span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.NoOfPiece, new { @class = "form-control", @Placeholder = "Refund Piece", @onkeypress = "return isNumberKey(event);", @onchange = "return checkavailable()" })
                                    </div>

                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormPassword">Amount <span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.Balance, new { @class = "form-control", @Placeholder = "Amount", @onkeypress = "return isNumberKey(event);" })
                                    </div>

                                    @*<div class="form-group col-sm-4">
                                        <label for="simpleFormPassword">Contact No </label>
                                        @Html.TextBoxFor(m => m.Mobile, new { @class = "form-control", @placeholder = "Contact Number", @onkeypress = "return isNumberKey(event);", @Maxlength = "8", @Minlength = "8", @readonly = "true" })
                                    </div>*@


                                
                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormPassword">Refund Date <span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.RefundDate, new { @class = "form-control", @Placeholder = "Refund Date", @Readonly = "true" })
                                    </div>
                                </div>
                                <input type="submit" class="btn btn-primary" name="Save" value="Submit" onclick="return Validateform()">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
    function getBillNo() {
        $("#divload").css({ 'display': '' });
        var BillNo = $('#BillNo').val();
        debugger;

            $.ajax({
                url: '/SaleOrder/GetAvailableBill', type: 'post', dataType: 'json',
                data: { 'BillNo': BillNo },
                success: function (data) {
                    $("#divload").css({ 'display': 'none' });
                 if (data.Result == "yes") {
                     $("#AvailableNoOfPiece").val(data.NoOfPiece);
                     $("#Mobile").val(data.Mobile);
                        $("#BillNo").removeClass('errortext');
                        $("#AvailableNoOfPiece").removeClass('errortext');
                        $("#Mobile").removeClass('errortext');
                 }
                    else {
                      alert(data.Result);
                        $("#AvailableNoOfPiece").val('');
                        $("#AvailableNoOfPiece").addClass('errortext');
                        $("#Mobile").val('');
                        $("#Mobile").addClass('errortext');
                        $("#BillNo").addClass('errortext');
                        $('#BillNo').focus();
                        $('#BillNo').val('');

                    }
                }
            });
        }
    function Validateform()
    {
        $("#divload").css({ 'display': '' })
        $(".errortext").removeClass("errortext");

        if ($("#BillNo").val() == "") {
            $("#BillNo").addClass('errortext');
            $("#BillNo").focus();
            return false;
        }
        //if ($("#PieceName").val() == "") {
        //    $("#PieceName").addClass('errortext');
        //    $("#PieceName").focus();
        //    return false;
        //}
        if ($("#NoOfPiece").val() == "") {
            $("#NoOfPiece").addClass('errortext');
            $("#NoOfPiece").focus();
            return false;
        }
        if ($("#Mobile").val() == "") {
            $("#Mobile").addClass('errortext');
            $("#Mobile").focus();
            return false;
        }
        if ($("#Balance").val() == "") {
            $("#Balance").addClass('errortext');
            $("#Balance").focus();
            return false;
        }
        if ($("#RefundDate").val() == "") {
            $("#RefundDate").addClass('errortext');
            $("#RefundDate").focus();
            return false;
        }

    }
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode;
        if (charCode != 46 && charCode > 31
          && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
    function checkavailable()
    {
        var availablepiece = $("#AvailableNoOfPiece").val();
        var refuncdpiece = $("#NoOfPiece").val();
        if (Number(refuncdpiece) > Number(availablepiece)) {
            alert('You Can Not Refund Greater Than Available Piece');
            $("#NoOfPiece").val('');
            $("#NoOfPiece").addClass('errortext');
            $("#NoOfPiece").focus();
            return false;
        }
    }

</script>

<script src="~/plugins/flatpickr/flatpickr.js"></script>
<script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script>
    var f3 = flatpickr(document.getElementById('RefundDate'),
        {
            dateFormat: "d/m/Y",
        });
</script>

WafaTailor/Views/SaleOrder/RefundSaleOrderList.cshtml
@model WafaTailor.Models.SaleOrder

@{
    ViewBag.Title = "RefundSaleOrderList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("RefundSaleOrderList", "SaleOrder", FormMethod.Post, new { @id = "form", @enctype = "multipart/form-data" }))
{
   <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class="pull-left">
                        @*  <div class="page-title">Bill List</div>*@
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-head">
                            <header>Refund SaleOrder List</header>
                            <span class="text-danger">
                                @TempData["Order"]
                            </span>
                            <a href="/SaleOrder/RefundSaleOrder" class="btn btn-primary pull-right"><i class="fa fa-arrow-left"></i> Back TO Refund Order</a>
                        </div>

                        <div class="card-body">
                            <table style="width: 100%" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>Sr.No.</th>
                                        <th>Bill Number</th>
                                        <th>Return Piece</th>
                                        @*<th>Contact Number</th>*@
                                        <th>Amount</th>
                                        <th>Refund Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstList != null)
                                        {
                                            int i = 1;
                                            foreach (var item in Model.lstList)
                                            {
                                                <tr>
                                                    <td>@i</td>
                                                    <td>@item.BillNo</td>
                                                    <td>@item.NoOfPiece</td>
                                                    @*<td>@item.Mobile</td>*@
                                                    <td>@item.Balance</td>
                                                    <td>@item.RefundDate</td>
                                                    <td>
                                                        <a target="_blank" href="/SaleOrder/PrintRefundSaleOrder?RefundId=@item.RefundId" class="tblDelBtn">
                                                            <i class="btn btn-primary" title="Print">Print</i>
                                                        </a>

                                                    </td>
                                                </tr>
                                                i = i + 1;
                                            }
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}