WafaTailor/Controllers/ShopController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WafaTailor.Filter;
using WafaTailor.Models;

namespace WafaTailor.Controllers
{
    public class ShopController : ShopBaseController
    {
        // GET: Shop
        public ActionResult ShopDashBoard()
        {
            return View();
        }
        public ActionResult ShopSaleOrder(Shop obj)
        {
            #region Customer
            List<SelectListItem> ddlcustomer = new List<SelectListItem>();
            DataSet ds1 = obj.GetCustomerDetails();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                int count = 0;
                foreach (DataRow r in ds1.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        ddlcustomer.Add(new SelectListItem { Text = "Select Customer", Value = "0" });
                    }
                    ddlcustomer.Add(new SelectListItem { Text = r["CustomerName"].ToString(), Value = r["PK_UserId"].ToString() });
                    count++;
                }
            }
            ViewBag.ddlcustomer = ddlcustomer;
            #endregion
            return View(obj);
        }
        [HttpPost]
        public JsonResult SaveSaleOrder(Shop order, string dataValue)
        {
            try
            {
                //order.SaleOrderDate = string.IsNullOrEmpty(order.SaleOrderDate) ? null : Common.ConvertToSystemDate(order.SaleOrderDate, "dd/MM/yyyy");
                string Name = "";
                string Piece = "";
                string OriginalPrice = "";
                string Discount = "";
                string FinalPrice = "";
                string SaleDate = "";
                string Description = "";
                //int rowsno = 0;
                var isValidModel = TryUpdateModel(order);
                var jss = new JavaScriptSerializer();
                var jdv = jss.Deserialize<dynamic>(dataValue);

                DataTable dtorder = new DataTable();
                dtorder.Columns.Add("Name");
                dtorder.Columns.Add("Piece");
                dtorder.Columns.Add("OriginalPrice");
                dtorder.Columns.Add("Discount");
                dtorder.Columns.Add("FinalPrice");
                dtorder.Columns.Add("SaleDate");
                dtorder.Columns.Add("Description");
                //dtorder.Columns.Add("rowsno");
                DataTable dt = new DataTable();
                dt = JsonConvert.DeserializeObject<DataTable>(jdv["dataValue"]);
                int numberOfRecords = dt.Rows.Count;
                //foreach (DataRow row in dt.Rows)

                foreach (DataRow row in dt.Rows)
                {
                    //Name = row["Name"].ToString();
                    Name = "";
                    Piece = row["Piece"].ToString();
                    OriginalPrice = row["OriginalPrice"].ToString();
                    Discount = row["Discount"].ToString();
                    FinalPrice = row["NetAmount"].ToString();
                    //SaleDate = row["SaleDate"].ToString();
                  SaleDate = string.IsNullOrEmpty(row["SaleDate"].ToString()) ? null : Common.ConvertToSystemDate(row["SaleDate"].ToString(), "dd/MM/yyyy");
                    Description = row["Description"].ToString();
                    //
                    //rowsno = rowsno + 1;
                    dtorder.Rows.Add(Name, Piece, OriginalPrice, Discount, FinalPrice, SaleDate,Description);
                }
                order.dt = dtorder;
               
                order.AddedBy = Session["Pk_userId"].ToString();
                DataSet ds = order.SaveSaleOrder();
                if (ds != null && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0][0].ToString() == "1")
                    {
                        order.Result = "Yes";
                    }
                    else if (ds.Tables[0].Rows[0][0].ToString() == "0")
                    {
                        order.Result = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                    }
                }
                else
                {
                    order.Result = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                }
            }
            catch (Exception ex)
            {

                order.Result = ex.Message;
            }

            return new JsonResult { Data = new { status = order.Result } };
        }
        public ActionResult ShopSaleOrderList(Shop model)
        {
            List<Shop> lst = new List<Shop>();
            model.AddedBy = Session["Pk_userId"].ToString();
            model.ShopLoginId = Session["LoginId"].ToString();
            DataSet ds = model.GetShopSaleOrderDetails();
            if (ds != null && ds.Tables[0].Rows.Count > 0 && ds.Tables.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Shop obj = new Shop();
                    obj.SaleOrderId = r["Fk_SaleOrderId"].ToString();
                    obj.BillNo = r["BillNo"].ToString();
                    obj.TotalDeliveredPiece = r["TotalPiece"].ToString();
                    obj.NetAmount = r["TotalAmount"].ToString();
                    obj.customerName = r["customerName"].ToString();
                    obj.Mobile = r["Mobile"].ToString();
                    //obj.SalesOrderNo = r["SalesOrderNo"].ToString();
                    lst.Add(obj);
                }
                model.lstShopRegistration = lst;
            }
            return View(model);
        }
        public ActionResult PrintShopSaleOrder(String SaleOrderId)
        {
            List<Shop> lstShopSaleOrderDetails = new List<Shop>();
            Shop model = new Shop();
            model.SaleOrderId = SaleOrderId;
            DataSet ds = model.PrintShopSO();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                ViewBag.CustomerName = ds.Tables[0].Rows[0]["Name"].ToString();
                ViewBag.CustomerMobile = ds.Tables[0].Rows[0]["Mobile"].ToString();
                ViewBag.CustomerAddress = ds.Tables[0].Rows[0]["Address"].ToString();
                ViewBag.Email = ds.Tables[0].Rows[0]["Email"].ToString();
                ViewBag.BillNo = ds.Tables[0].Rows[0]["BillNo"].ToString();
            }
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[1].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[1].Rows)
                {
                    model.SaleDate = ds.Tables[1].Rows[0]["SaleDate"].ToString();
                    model.PieceName = ds.Tables[1].Rows[0]["PieceName"].ToString();
                    model.NoOfPiece = ds.Tables[1].Rows[0]["NoOfPiece"].ToString();
                    model.OriginalPrice = ds.Tables[1].Rows[0]["OriginalPrice"].ToString();
                    model.Discount = ds.Tables[1].Rows[0]["Discount"].ToString();
                    model.FinalPrice = ds.Tables[1].Rows[0]["FinalPrice"].ToString();
                    lstShopSaleOrderDetails.Add(model);
                }
                model.lstshopsaleorder = lstShopSaleOrderDetails;
               ViewBag.FinalPrice = double.Parse(ds.Tables[1].Compute("sum(FinalPrice)", "").ToString()).ToString("n2");
            }

            return View(model);
        }
        //public ActionResult DeleteShopSaleOrder(String SaleOrderId)
        //{
        //    Shop obj = new Shop();
        //    try
        //    {
        //        obj.SaleOrderId = SaleOrderId;
        //        DataSet ds = obj.DeleteShopSaleOrder();
        //        if (ds != null && ds.Tables.Count > 0)
        //        {
        //            if (ds.Tables[0].Rows[0][0].ToString() == "1")
        //            {
        //                TempData["ShopSaleOrder"] = "Shop Sale Order Deleted Successfully!";
        //            }
        //            else
        //            {
        //                TempData["ShopSaleOrder"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
        //            }
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["ShopSaleOrder"] = ex.Message;
        //    }
        //    return RedirectToAction("ShopSaleOrderList", "Shop");
        //}
        public ActionResult GetcustomerList()
        {
            Shop obj = new Shop();
            List<Shop> lst = new List<Shop>();
            DataSet ds = obj.GetCustomerDetail();
            if (ds != null && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Shop objList = new Shop();
                    objList.Name = dr["CustomerName"].ToString();
                    objList.Mobile = dr["Mobile"].ToString();
                    objList.LoginId = dr["LoginId"].ToString();
                    lst.Add(objList);
                }
            }
            return Json(lst, JsonRequestBehavior.AllowGet);
        }
        public ActionResult BillEntry(Shop model, string BillId, string PaymentId)
        {
            #region Customer
            List<SelectListItem> ddlcustomer = new List<SelectListItem>();
            DataSet ds1 = model.GetCustomerDetails();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                int count = 0;
                foreach (DataRow r in ds1.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        ddlcustomer.Add(new SelectListItem { Text = "Select Customer", Value = "0" });
                    }

WafaTailor/Views/Shop/BillList.cshtml
@model WafaTailor.Models.Shop

@{
    ViewBag.Title = "BillList";
    Layout = "~/Views/Shared/_ShopLayout.cshtml";
}


<link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
<link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
@using (Html.BeginForm("BillList", "Shop", FormMethod.Post, new { @id = "form", @enctype = "multipart/form-data" }))
{
   <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class="pull-left">
                        @*  <div class="page-title">Bill List</div>*@
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-head">
                            <header>Bill List</header>
                            <span class="text-danger">
                                @TempData["Bill"]
                            </span>
                            <a href="/Shop/BillEntry" class="btn btn-primary pull-right"><i class="fa fa-arrow-left"></i> Back to Bill Entry</a>
                            @*<div class="tools">
                                    <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                    <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                                    <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                                </div>*@
                        </div>

                        <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label> From Date</label>
                                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @Placeholder = "DD/MM/YYYY", @readonly="true" })
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label> To Date</label>
                                            @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @Placeholder = "DD/MM/YYYY", @readonly = "true" })
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-3">
                                        <div class="form-group">
                                            <input class="btn btn-success pull-left mt-4" type="submit" value="Search" id="btnSearch" name="btnSearch" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <div class="card-body">
                            <table style="width: 100%" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>Customer Name</th>
                                        <th>Contact No</th>
                                        <th>Number Of Piece</th>
                                        <th>Original Price</th>
                                        <th>Bill Number</th>
                                        <th>Bill Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstList != null)
                                        {
                                            int i = 1;
                                            foreach (var item in Model.lstList)
                                            {
                                                <tr>
                                                    <td>@i</td>
                                                    <td>@item.Name</td>
                                                    <td>@item.Mobile</td>
                                                    <td>@item.NoOfPiece</td>
                                                    <td>@item.OriginalPrice</td>
                                                    <td>@item.BillNo</td>
                                                    <td>@item.BillDate</td>
                                                    <td>
                                                        <a target="_blank" href="/Shop/PrintBill?BillId=@item.BillId&&PaymentId=@item.Pk_BillPaymentId" class="tblDelBtn">
                                                            <i class="btn btn-secoundry" title="Print">Print</i>
                                                        </a>
                                                        <a href="/Shop/BillEntry?BillId=@item.BillId&&PaymentId=@item.Pk_BillPaymentId" class="tblDelBtn btn-sm">
                                                            <i class="btn btn-primary" title="Print">Edit</i>
                                                        </a>
                                                        @if (item.Balance > 0)
                                                        {
                                                            <a target="_blank" href="/Shop/BillPayment?BillId=@item.BillId&&PaymentId=@item.Pk_BillPaymentId" class="tblDelBtn">
                                                                <i class="btn btn-danger" title="Paid Bill">Paid Bill</i>
                                                            </a>
                                                        }
                                                    </td>
                                                </tr>
                                                i = i + 1;
                                            }
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@*<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script type="text/javascript">
    $('#FromDate').datepicker({
        format: 'dd/mm/yyyy',
        changeYear: true,
        changeMonth: true,
        maxDate: 0
    });
    $('#ToDate').datepicker({
        format: 'dd/mm/yyyy',
        changeYear: true,
        changeMonth: true,
        maxDate: 0
    });
</script>*@

<script src="~/plugins/flatpickr/flatpickr.js"></script>
<script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script src="~/BrainStewWebsite/assets/js/jquery.min.js"></script>
<script>
    var f3 = flatpickr(document.getElementById('FromDate'),
        {
            dateFormat: "d/m/Y",
        });
    var f3 = flatpickr(document.getElementById('ToDate'),
        {
            dateFormat: "d/m/Y",
        });
</script>

WafaTailor/Views/Shop/RefundShopSaleOrder.cshtml
@model WafaTailor.Models.Shop

@{
    ViewBag.Title = "RefundShopSaleOrder";
    Layout = "~/Views/Shared/_ShopLayout.cshtml";
}

<link href="~/plugins/flatpickr/flatpickr.css" rel="stylesheet" type="text/css">
<link href="~/plugins/flatpickr/custom-flatpickr.css" rel="stylesheet" type="text/css">
@using (Html.BeginForm("RefundShopSaleOrder", "Shop", FormMethod.Post, new { @Id = "form", @enctype = "multipart/Form-data" }))
{
    <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class="pull-left">
                        @*<div class="page-title"> Employee Registration</div>*@
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-12">
                    <div class="card card-box">
                        <div class="card-head">
                            <header>Refund Sale Order</header>
                            <span class="text-danger">
                                @TempData["Order"]
                            </span>
                            <a href="/Shop/RefundShopSaleOrderList" class="btn btn-primary pull-right mr-10 mt-1 mb-1"><i class="fa fa-arrow-left"></i> Back to List</a>
                        </div>
                        <div class="card-body" id="bar-parent">
                            <form>
                                <div class="row">
                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormPassword">Bill Number <span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.BillNo, new { @class = "form-control", @placeholder = "Bill Number", @onchange = "return getBillNo();" })
                                        @Html.HiddenFor(m => m.BillNo)
                                    </div>

                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormEmail">Total Piece<span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.AvailableNoOfPiece, new { @class = "form-control", @Placeholder = "Total Piece", @readonly = "true" })
                                    </div>

                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormEmail">Refund Piece<span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.NoOfPiece, new { @class = "form-control", @Placeholder = "Refund Piece", @onkeypress = "return isNumberKey(event);", @onchange = "return checkavailable()" })
                                    </div>

                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormPassword">Amount <span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.Balance, new { @class = "form-control", @Placeholder = "Amount", @onkeypress = "return isNumberKey(event);" })
                                    </div>

                                    @*<div class="form-group col-sm-4">
                                            <label for="simpleFormPassword">Contact No </label>
                                            @Html.TextBoxFor(m => m.Mobile, new { @class = "form-control", @placeholder = "Contact Number", @onkeypress = "return isNumberKey(event);", @Maxlength = "8", @Minlength = "8", @readonly = "true" })
                                        </div>*@



                                    <div class="form-group col-sm-4">
                                        <label for="simpleFormPassword">Refund Date <span style="color:red">*</span></label>
                                        @Html.TextBoxFor(m => m.RefundDate, new { @class = "form-control", @Placeholder = "Refund Date", @Readonly = "true" })
                                    </div>
                                </div>
                                <input type="submit" class="btn btn-primary" name="Save" value="Submit" onclick="return Validateform()">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
    function getBillNo() {
        $("#divload").css({ 'display': '' });
        var BillNo = $('#BillNo').val();
        debugger;

            $.ajax({
                url: '/Shop/GetAvailableBill', type: 'post', dataType: 'json',
                data: { 'BillNo': BillNo },
                success: function (data) {
                    $("#divload").css({ 'display': 'none' });
                 if (data.Result == "yes") {
                     $("#AvailableNoOfPiece").val(data.NoOfPiece);
                     $("#Mobile").val(data.Mobile);
                        $("#BillNo").removeClass('errortext');
                        $("#AvailableNoOfPiece").removeClass('errortext');
                        $("#Mobile").removeClass('errortext');
                 }
                    else {
                      alert(data.Result);
                        $("#AvailableNoOfPiece").val('');
                        $("#AvailableNoOfPiece").addClass('errortext');
                        $("#Mobile").val('');
                        $("#Mobile").addClass('errortext');
                        $("#BillNo").addClass('errortext');
                        $('#BillNo').focus();
                        $('#BillNo').val('');

                    }
                }
            });
        }
    function Validateform()
    {
        $("#divload").css({ 'display': '' })
        $(".errortext").removeClass("errortext");

        if ($("#BillNo").val() == "") {
            $("#BillNo").addClass('errortext');
            $("#BillNo").focus();
            return false;
        }
        //if ($("#PieceName").val() == "") {
        //    $("#PieceName").addClass('errortext');
        //    $("#PieceName").focus();
        //    return false;
        //}
        if ($("#NoOfPiece").val() == "") {
            $("#NoOfPiece").addClass('errortext');
            $("#NoOfPiece").focus();
            return false;
        }
        if ($("#Mobile").val() == "") {
            $("#Mobile").addClass('errortext');
            $("#Mobile").focus();
            return false;
        }
        if ($("#Balance").val() == "") {
            $("#Balance").addClass('errortext');
            $("#Balance").focus();
            return false;
        }
        if ($("#RefundDate").val() == "") {
            $("#RefundDate").addClass('errortext');
            $("#RefundDate").focus();
            return false;
        }

    }
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode;
        if (charCode != 46 && charCode > 31
          && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
    function checkavailable()
    {
        var availablepiece = $("#AvailableNoOfPiece").val();
        var refuncdpiece = $("#NoOfPiece").val();
        if (Number(refuncdpiece) > Number(availablepiece)) {
            alert('You Can Not Refund Greater Than Available Piece');
            $("#NoOfPiece").val('');
            $("#NoOfPiece").addClass('errortext');
            $("#NoOfPiece").focus();
            return false;
        }
    }

</script>

<script src="~/plugins/flatpickr/flatpickr.js"></script>
<script src="~/plugins/flatpickr/custom-flatpickr.js"></script>
<script>
    var f3 = flatpickr(document.getElementById('RefundDate'),
        {
            dateFormat: "d/m/Y",
        });
</script>

WafaTailor/Views/Shop/RefundShopSaleOrderList.cshtml
@model WafaTailor.Models.Shop

@{
    ViewBag.Title = "RefundShopSaleOrderList";
    Layout = "~/Views/Shared/_ShopLayout.cshtml";
}

@using (Html.BeginForm("RefundShopSaleOrderList", "Shop", FormMethod.Post, new { @id = "form", @enctype = "multipart/form-data" }))
{
   <!-- start page content -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class="pull-left">
                        @*  <div class="page-title">Bill List</div>*@
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-head">
                            <header>Refund SaleOrder List</header>
                            <span class="text-danger">
                                @TempData["Order"]
                            </span>
                            <a href="/Shop/RefundShopSaleOrder" class="btn btn-primary pull-right"><i class="fa fa-arrow-left"></i> Back TO Refund Order</a>
                        </div>

                        <div class="card-body">
                            <table style="width: 100%" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>Sr.No.</th>
                                        <th>Bill Number</th>
                                        <th>Return Piece</th>
                                        @*<th>Contact Number</th>*@
                                        <th>Amount</th>
                                        <th>Refund Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstList != null)
                                        {
                                            int i = 1;
                                            foreach (var item in Model.lstList)
                                            {
                                                <tr>
                                                    <td>@i</td>
                                                    <td>@item.BillNo</td>
                                                    <td>@item.NoOfPiece</td>
                                                    @*<td>@item.Mobile</td>*@
                                                    <td>@item.Balance</td>
                                                    <td>@item.RefundDate</td>
                                                    <td>
                                                        <a target="_blank" href="/Shop/PrintRefundShopSaleOrder?RefundId=@item.RefundId" class="tblDelBtn">
                                                            <i class="btn btn-primary" title="Print">Print</i>
                                                        </a>

                                                    </td>
                                                </tr>
                                                i = i + 1;
                                            }
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WafaTailor/Views/Shop/ShopDashBoard.cshtml
@model WafaTailor.Models.Shop

@{
    ViewBag.Title = "ShopDashBoard";
    Layout = "~/Views/Shared/_ShopLayout.cshtml";
}

<h2>ShopDashBoard</h2>